# Generated by Django 4.2.5 on 2023-10-03 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender name')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=7, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_user/', verbose_name='Avatar User'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='About Interests'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_lat',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Location Latitude'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_lng',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Location Longitude'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='CustomUserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='User Images')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='User Identity')),
            ],
            options={
                'verbose_name': 'Custom User Image',
                'verbose_name_plural': 'Custom User Images',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='authentification.gender', verbose_name='Gender'),
        ),
    ]
